---
#tasks file for routing
- block:
  - name: Include OSPF routing
    include_tasks: ospf.yml
    tags: ospf

  - name: Include LDP 
    include_tasks: ldp.yml
    tags: ldp

  - name: Include MPLS
    include_tasks: mpls.yml
    tags: mpls

# - name: Include BGP routing
#   include_tasks: bgp.yml

